### ISSUE TITLE
Wie updaten wir unsere Daten?

### ISSUE THREAD

**Issue by FrtZgwL** [FrtZgwL/CoronaBot#2]
Die aktuellen ".csv" Dateien sollen, wann immer man `data_manager.update_data()` aufruft, von [Johns Hopkins](https://github.com/CSSEGISandData/COVID-19) in den `data/` Ordner runtergeladen werden. Wie machen wir das?

Können wir auch die anderen Daten (Populationen, Sterberaten) updaten? Ist das sinnvoll?

**Comment by lipilli** [comment]
Vorschlag: 

Wir speichern die Daten: Tote, Erkrankte, Geheilte, Aktive in jeweils einem Array und appenden täglich die neusten daten.

**Comment by FrtZgwL** [comment]
Ich frag mich gerade, wie wir herausfinden können, welche Daten neu dazu gekommen sind. Müssten wir dazu nicht erst alle JH-Daten mit unseren Daten vom Vortag vergleichen? Wenn wir nämlich eh jeden Tag alle JH-Daten downloaden müssen, können wir auch gleich jeden Tag die ganzen Data-Frames und so neu aufsetzen. Was meinst du @lipilli?

Und ich dachte, du speicherst die Daten in DataFrames? Wie hängen die mit den Arrays zusammen?
