### ISSUE TITLE
Data Updater: Datenziehen überarbeiten

### ISSUE THREAD

**Issue by lipilli** [FrtZgwL/CoronaBot#20]
Es scheint so als würden die Timesries doch jeden Tag überarbeitet. Die Daten müssen aber trotzdem jeden tag heruntergeladen werden. Es kann sein, dass die Daten von den Vortagen im Nachhinein geändert werden. 

**Der Data updater soll:** 

* Jeden Tag folgende timeseries herunterladen als csv: 
> time_series_covid19_confirmed_global.csv
> time_series_covid19_deaths_global.csv
> time_series_covid19_recovered_global.csv

* Die jeweilige CSV in ein pandas DF umformen: 
```python
#Eg:
df_deaths_global = pd.DataFrame(pd.read_csv(hop/"csse_covid_19_time_series"/time_series_covid19_deaths_global.csv))
```

* Unwichtige spalten löschen
``` python
df = df_deaths_global.drop(['Province/State', 'Lat', 'Long'], axis=1) 
```

* Die die Zeilen die den gleichen Index haben (Land) zaufsummieren):
``` python
df2=df.reset_index().groupby("Country/Region").sum().drop(['index'], axis=1)
```

**Comment by FrtZgwL** [comment]
@lipilli hab's nach deinem Vorschlag implementiert. Ich versteh das Zusammenfassen noch nicht ganz, würdest du da nochmal drüber schauen? :)

**Comment by lipilli** [comment]
Hab's überarbeitet
