### ISSUE TITLE
Data Updater: Data Frame für Aktive Cases:

### ISSUE THREAD

**Issue by lipilli** [FrtZgwL/CoronaBot#22]
Ziel ist ein DF das so aussieht wie alle anderen 3 Data frames (Deaths, confirmed und recovered global")

**TO DO:**
* Funktion erstellen die die aktiven Cases ausrechnet (Hier wirlich nur die Formel)

* Variablen für jedes Land aus den richtigen spalten und Zeilen der 3 Anderen Data Frames ziehen

Es gibt hierfür verschiedene Herangehensweisen:
Für eine habe ich Bilder in die Gruppe geschickt.

**Comment by FrtZgwL** [comment]
![IMAGE 2020-04-17 00:15:10](https://user-images.githubusercontent.com/7171862/79511920-938d6180-8040-11ea-9fba-042d86bf7082.jpg)
![IMAGE 2020-04-17 00:15:11](https://user-images.githubusercontent.com/7171862/79511925-95572500-8040-11ea-9e2d-402fe55582d7.jpg)
