### ISSUE TITLE
Wie säubern wir unsere Daten?

### ISSUE THREAD

**Issue by FrtZgwL** [FrtZgwL/CoronaBot#3]
Nordamerika heißt mal "USA", mal "US.", Südkorea heißt manchmal auch "S. Korea", usw. Wie schaffen wir es, unsere Daten einheitlich zu speichern?

**Comment by lipilli** [comment]
Ich vermute ich muss mir alle daten mal anschauen, und dann für jedes Land ein Dictionary anlegen be der jeder Ländername auf alle seine verschiedenn Möglichkeiten gemappt wird, uff

**Comment by FrtZgwL** [comment]
Hui! Ja das klingt nach ner ganz schönen Aufgabe. Du kannst ja mal stichprobenweise in die relevantesten Länder reinspicken und damit die grobe Struktur von diesem Dictionary festlegen. Und dann sagst du Bescheid und wir setzen uns zu dritt hin und schauen, wie wir die Datenmasse gebändigt kriegen.

(Ich nehme an einfach `country_names` von jedem Ländernamen, wie er in den Tabllen vorkommt, zu dem, den wir wollen in `const.py`?)
