### ISSUE TITLE
Verständliche Menü-Namen und Antworten

### ISSUE THREAD

**Issue by FrtZgwL** [FrtZgwL/CoronaBot#9]
Die Antworten des Bots und die Menü-Namen nicht immer knapp, nicht immer konsistent und nicht immer gut verständlich. Hier sollten wir intuitivere Texte schreiben.

**Comment by lipilli** [comment]
Ich würde die Welcome Messge noch etwas ausführlicher schreiben. Und dann die Buttens wie folgt ändern:

**Welcome Message:**
"Willkommen! Ich bin der CoronaBot. 
Ich liefere dir Grafiken auf denen du den Verlauf der Coronapandemie in verschiednen Ländern vergleichen kannst. 

Ich zeige dir Informationen über die Corona Toten, Geheilten, Erkrankten und uber die aktuell Erkrankten.

Die Verlaufe zeige ich dir so für jedes Land an: 
- In Relation zu seiner Bevölkerung anscheuen (pro 100.000 Eeinwohner). 
- In Relation zu seiner Bevölkerung seit dem Ausbruch (100. Fall) //_vlt nehmen wir hier doch die Absolute Zahl, das macht die Auswahl einfacher und differenziert die Punkte von einander.._

Außerdem zeige ich dir das Verhältnis der an Corona Gestorbenen zu  allen Gestorbenen seit beginn der Pandemie.
_Anmerkung: Für diese Statistik mache ich die annahmen, dass Corona Tote auch nur an Corona gestorben sind und, dass seit Beginn der Pandemie genau so viele Menschen gestorben sind wie im Duchschnitt der vergangenen Jahre _


**Dann kann man die Buttens Anpassen:**

je 1000 EW --> Verhältnis 
Ab 100. Fall --> Beginn 
Crona/ durchsnittliche Tite --> Gestorben: Corona vs Alle  

** Und dann noch das:**
Klick dich gerne durch meine Menüs."

**Comment by FrtZgwL** [comment]
Danke für den Vorschlag! :)

Absolute Zahlen seit Ausbruch finde ich auch besser, habs mal so reingeschrieben.

Ich habs jetzt fast genau so übernommen, habe nur bisschen expliziter gemacht, dass der Bot drei Funktionen hat. Dazu hab ich die Liste um den dritten Punkt ergänzt. Und ich hab "Kuchen" als Namen für den dritten Punkt genommen, damit wir einheitlich Ein-Wort-Namen haben.
